
schema={
        "type":"",
        "title":"",
        "description":"",
        "author":"",
        "post_date":"",
        "event_date":"",
        "mediaurl":"",
        "like":[],
        "comment":[],
        "ismedia":""
}
commentSchema_=[
  {
    "id":"",
    "comment":""
  }
]
imageCreate_=["type","description","author","mediaurl","ismedia"]
eventCreate_=["type","title","description","author","event_date","ismedia"]
textCreate_=["type","description","author","ismedia"]
like_=["id"]
comment_=['id','comment']
deleteComment_=['userid','postid','comment']